---
apiVersion: capabilities.3scale.net/v1beta1
kind: Backend
metadata:
  name: backend-uk-brel-13
  namespace: "%NAMESPACE%"
  labels:
    api: uk-brel-13
spec:
  name: Branch Locator Backend
  systemName: backend_uk_brel_13
  description: >-
    UK Open Data Branches Locator v1.3 backend referring to Mock endpoint provided
    by Microcks on the 2d0b cluster.
  providerAccountRef:
    name: "%PROVIDER_ACCOUNT_REF%"
  privateBaseURL: >-
    %PRIVATE_BASE_URL%/version=1.2+Branch+Data+Collection/1